"""Public API surface for xtm-oaev-sdk. 107 symbols."""

__version__ = "0.1.0"

# --- Common (shared) ---
from xtm_oaev_sdk.contracts.common import (
    AppLoggerProtocol,
    AssetCategory,
    AssetCriticality,
    AssetSubCategory,
    BaseClient,
    CloudProvider,
    ConfigurationError,
    DaemonProtocol,
    EncodedId,
    OpenAEVAuthenticationError,
    OpenAEVCreateError,
    OpenAEVDeleteError,
    OpenAEVError,
    OpenAEVGetError,
    OpenAEVHeadError,
    OpenAEVHttpError,
    OpenAEVListError,
    OpenAEVParsingError,
    OpenAEVUpdateError,
    RedirectError,
    RequiredOptional,
    SecurityDomains,
    SignatureTransmissionError,
)
from xtm_oaev_sdk._core.common import (
    AppLogger,
    CustomJsonFormatter,
    EnhancedJSONEncoder,
    copy_dict,
    data_to_temp_file,
    is_memory_certificate,
    logger,
    on_http_error,
    remove_none_from_dict,
    setup_logging_config,
    ssl_cert_chain,
    ssl_verify_locations,
)

# --- Configuration ---
from xtm_oaev_sdk.contracts.configuration import (
    BaseConfigModel,
    CONFIGURATION_TYPES,
    ConfigurationHint,
    ConfigurationProtocol,
    HttpUrlToString,
    LogLevelToLower,
    TimedeltaInSeconds,
)
from xtm_oaev_sdk._core.configuration import (
    ConfigLoaderCollector,
    ConfigLoaderOAEV,
    Configuration,
    ConnectorConfigSchemaGenerator,
    DictionarySource,
    EnvironmentSource,
    SettingsLoader,
)

# --- Contracts (scenarios) ---
from xtm_oaev_sdk.contracts.contracts import (
    Contract,
    ContractAsset,
    ContractAssetGroup,
    ContractAttachment,
    ContractBuilderProtocol,
    ContractCardinality,
    ContractCardinalityElement,
    ContractCheckbox,
    ContractConfig,
    ContractElement,
    ContractExpectationType,
    ContractExpectations,
    ContractFieldKey,
    ContractFieldType,
    ContractOutputElement,
    ContractOutputType,
    ContractPayload,
    ContractSelect,
    ContractTeam,
    ContractText,
    ContractTextArea,
    ContractTuple,
    ContractVariable,
    Domain,
    Expectation,
    LinkedFieldModel,
    SupportedLanguage,
    VariableType,
)
from xtm_oaev_sdk._core.contracts import (
    ContractBuilder,
    VariableHelper,
    prepare_contracts,
)

# --- Signatures ---
from xtm_oaev_sdk.contracts.signatures import (
    CloudInjectorConfig,
    ExecutionDetails,
    ExecutionSignature,
    ExpectationSignatureGroup,
    ExtraSignatureData,
    InjectExecutionActions,
    InjectorConfig,
    MatchTypes,
    NetworkInjectorConfig,
    SignatureCallbackPayload,
    SignatureExpectationType,
    SignatureManagerProtocol,
    SignatureOutputStructure,
    SignaturePayload,
    SignatureTarget,
    SignatureTransportProtocol,
    SignatureTypes,
    SignatureValue,
    TargetSignatures,
    ToolErrorInfo,
    ToolOutput,
    ToolTimeoutInfo,
)
from xtm_oaev_sdk._core.signatures import (
    SignatureManager,
    SignatureMatch,
    SignatureType,
    build_network_configs,
)

__all__ = [
    "__version__",
    # Common: errors
    "ConfigurationError",
    "OpenAEVAuthenticationError",
    "OpenAEVCreateError",
    "OpenAEVDeleteError",
    "OpenAEVError",
    "OpenAEVGetError",
    "OpenAEVHeadError",
    "OpenAEVHttpError",
    "OpenAEVListError",
    "OpenAEVParsingError",
    "OpenAEVUpdateError",
    "RedirectError",
    "SignatureTransmissionError",
    "on_http_error",
    # Common: utils
    "AppLogger",
    "AppLoggerProtocol",
    "CustomJsonFormatter",
    "EncodedId",
    "EnhancedJSONEncoder",
    "RequiredOptional",
    "copy_dict",
    "logger",
    "remove_none_from_dict",
    "setup_logging_config",
    # Common: protocols
    "BaseClient",
    "DaemonProtocol",
    # Common: ssl
    "data_to_temp_file",
    "is_memory_certificate",
    "ssl_cert_chain",
    "ssl_verify_locations",
    # Common: enums
    "AssetCategory",
    "AssetCriticality",
    "AssetSubCategory",
    "CloudProvider",
    "SecurityDomains",
    # Configuration
    "BaseConfigModel",
    "CONFIGURATION_TYPES",
    "ConfigLoaderCollector",
    "ConfigLoaderOAEV",
    "Configuration",
    "ConfigurationHint",
    "ConfigurationProtocol",
    "ConnectorConfigSchemaGenerator",
    "DictionarySource",
    "EnvironmentSource",
    "HttpUrlToString",
    "LogLevelToLower",
    "SettingsLoader",
    "TimedeltaInSeconds",
    # Contracts (scenarios)
    "Contract",
    "ContractAsset",
    "ContractAssetGroup",
    "ContractAttachment",
    "ContractBuilder",
    "ContractBuilderProtocol",
    "ContractCardinality",
    "ContractCardinalityElement",
    "ContractCheckbox",
    "ContractConfig",
    "ContractElement",
    "ContractExpectationType",
    "ContractExpectations",
    "ContractFieldKey",
    "ContractFieldType",
    "ContractOutputElement",
    "ContractOutputType",
    "ContractPayload",
    "ContractSelect",
    "ContractTeam",
    "ContractText",
    "ContractTextArea",
    "ContractTuple",
    "ContractVariable",
    "Domain",
    "Expectation",
    "LinkedFieldModel",
    "SupportedLanguage",
    "VariableHelper",
    "VariableType",
    "prepare_contracts",
    # Signatures
    "CloudInjectorConfig",
    "ExecutionDetails",
    "ExecutionSignature",
    "ExpectationSignatureGroup",
    "ExtraSignatureData",
    "InjectExecutionActions",
    "InjectorConfig",
    "MatchTypes",
    "NetworkInjectorConfig",
    "SignatureCallbackPayload",
    "SignatureExpectationType",
    "SignatureManager",
    "SignatureManagerProtocol",
    "SignatureMatch",
    "SignatureOutputStructure",
    "SignaturePayload",
    "SignatureTarget",
    "SignatureTransportProtocol",
    "SignatureType",
    "SignatureTypes",
    "SignatureValue",
    "TargetSignatures",
    "ToolErrorInfo",
    "ToolOutput",
    "ToolTimeoutInfo",
    "build_network_configs",
]
