# -*- coding: utf-8 -*-
"""Canonical asset taxonomy for OpenAEV (mirrors the backend enums).

These give producers (collectors, custom integrations) a single, typed vocabulary for the
two-level asset categorization (category + subcategory), criticality and cloud provider, instead
of free-form strings. They are plain ``str`` enums so they can be dropped straight into the dict
payloads sent to the API.
"""

from enum import Enum


class AssetCategory(str, Enum):
    HOST = "HOST"
    CONTAINER_WORKLOAD = "CONTAINER_WORKLOAD"
    CLOUD_RESOURCE = "CLOUD_RESOURCE"
    WEB_APPLICATION = "WEB_APPLICATION"
    NETWORK_DEVICE = "NETWORK_DEVICE"
    MOBILE_DEVICE = "MOBILE_DEVICE"
    IOT_OT_DEVICE = "IOT_OT_DEVICE"
    IDENTITY = "IDENTITY"
    SAAS_APPLICATION = "SAAS_APPLICATION"
    AI_TARGET = "AI_TARGET"
    SECURITY_PLATFORM = "SECURITY_PLATFORM"
    GENERIC_ASSET = "GENERIC_ASSET"


class AssetSubCategory(str, Enum):
    # HOST
    SERVER = "SERVER"
    WORKSTATION = "WORKSTATION"
    LAPTOP = "LAPTOP"
    VIRTUAL_MACHINE = "VIRTUAL_MACHINE"
    HYPERVISOR = "HYPERVISOR"
    MAINFRAME = "MAINFRAME"
    THIN_CLIENT = "THIN_CLIENT"
    # CONTAINER_WORKLOAD
    CONTAINER = "CONTAINER"
    CONTAINER_IMAGE = "CONTAINER_IMAGE"
    KUBERNETES_POD = "KUBERNETES_POD"
    KUBERNETES_CLUSTER = "KUBERNETES_CLUSTER"
    KUBERNETES_NODE = "KUBERNETES_NODE"
    SERVERLESS_FUNCTION = "SERVERLESS_FUNCTION"
    # CLOUD_RESOURCE
    COMPUTE = "COMPUTE"
    STORAGE = "STORAGE"
    DATABASE = "DATABASE"
    NETWORKING = "NETWORKING"
    SERVERLESS = "SERVERLESS"
    CONTAINER_REGISTRY = "CONTAINER_REGISTRY"
    KUBERNETES = "KUBERNETES"
    IAM_PRINCIPAL = "IAM_PRINCIPAL"
    SECRETS_KEY_MGMT = "SECRETS_KEY_MGMT"
    MESSAGING_QUEUE = "MESSAGING_QUEUE"
    ANALYTICS_DATA = "ANALYTICS_DATA"
    AI_ML_SERVICE = "AI_ML_SERVICE"
    IAC_TEMPLATE = "IAC_TEMPLATE"
    CLOUD_OTHER = "CLOUD_OTHER"
    # WEB_APPLICATION
    WEBSITE = "WEBSITE"
    WEB_API = "WEB_API"
    SINGLE_PAGE_APP = "SINGLE_PAGE_APP"
    GRAPHQL_API = "GRAPHQL_API"
    WEB_SERVICE = "WEB_SERVICE"
    MICROSERVICE = "MICROSERVICE"
    # NETWORK_DEVICE
    ROUTER = "ROUTER"
    SWITCH = "SWITCH"
    FIREWALL = "FIREWALL"
    LOAD_BALANCER = "LOAD_BALANCER"
    VPN_GATEWAY = "VPN_GATEWAY"
    WIRELESS_AP = "WIRELESS_AP"
    PROXY = "PROXY"
    DNS_SERVER = "DNS_SERVER"
    DHCP_SERVER = "DHCP_SERVER"
    SAN_NAS = "SAN_NAS"
    NETWORK_OTHER = "NETWORK_OTHER"
    # MOBILE_DEVICE
    SMARTPHONE = "SMARTPHONE"
    TABLET = "TABLET"
    # IOT_OT_DEVICE
    IOT_SENSOR = "IOT_SENSOR"
    IP_CAMERA = "IP_CAMERA"
    GATEWAY = "GATEWAY"
    POINT_OF_SALE = "POINT_OF_SALE"
    MEDIA_DEVICE = "MEDIA_DEVICE"
    PLC = "PLC"
    RTU = "RTU"
    HMI = "HMI"
    SCADA_HISTORIAN = "SCADA_HISTORIAN"
    MEDICAL_DEVICE = "MEDICAL_DEVICE"
    PRINTER_PERIPHERAL = "PRINTER_PERIPHERAL"
    BUILDING_MGMT = "BUILDING_MGMT"
    # IDENTITY
    USER_ACCOUNT = "USER_ACCOUNT"
    SERVICE_ACCOUNT = "SERVICE_ACCOUNT"
    GROUP = "GROUP"
    ROLE = "ROLE"
    SHARED_MAILBOX = "SHARED_MAILBOX"
    NON_HUMAN_IDENTITY = "NON_HUMAN_IDENTITY"
    # SAAS_APPLICATION
    SAAS_APP = "SAAS_APP"
    SAAS_TENANT = "SAAS_TENANT"
    # AI_TARGET
    LLM_MODEL = "LLM_MODEL"
    AI_AGENT = "AI_AGENT"
    MCP_SERVER = "MCP_SERVER"
    RAG_PIPELINE = "RAG_PIPELINE"
    # SECURITY_PLATFORM
    EDR = "EDR"
    XDR = "XDR"
    SIEM = "SIEM"
    SOAR = "SOAR"
    NDR = "NDR"
    ISPM = "ISPM"
    LLM_FIREWALL = "LLM_FIREWALL"
    AI_GATEWAY = "AI_GATEWAY"


class CloudProvider(str, Enum):
    AWS = "AWS"
    AZURE = "AZURE"
    GCP = "GCP"
    OCI = "OCI"
    ALIBABA = "ALIBABA"
    KUBERNETES = "KUBERNETES"
    OTHER = "OTHER"


class AssetCriticality(str, Enum):
    VERY_HIGH = "VERY_HIGH"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    UNKNOWN = "UNKNOWN"
